/**
 * Integration test stub — {{FEATURE}} (change: {{CHANGE}})
 * Stack: Spring Boot + PostgreSQL + Kafka (Testcontainers)
 * Auto-generated by testspec. Fill in HTTP calls and DB/Kafka assertions.
 */

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.containers.KafkaContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.utility.DockerImageName;
import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Testcontainers
class {{FEATURE_CAMEL}}IntegrationTest {

    @Container
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:16-alpine");

    @Container
    static KafkaContainer kafka = new KafkaContainer(DockerImageName.parse("confluentinc/cp-kafka:7.4.0"));

    @Autowired
    TestRestTemplate restTemplate;

    // {{SCENARIOS}}

    @Test
    void ctPlaceholder_replaceWithRealCT() {
        // Input: (from tests.md CT input field)
        // Expected output: (from tests.md CT expected output field)
        // DB validation: (from tests.md CT DB validation field)
        assertThat(postgres.isRunning()).isTrue();
        assertThat(kafka.isRunning()).isTrue();
    }
}
