"""
{{CT_ID}} — {{TITLE}}
Feature: {{FEATURE}}
Auto-generated by testspec. Fill in arrange/act/assert.
"""

import pytest


class Test{{CT_ID}}:
    def setup_method(self):
        # arrange: set up state from spec precondition
        pass

    def test_{{CT_ID_LOWER}}(self):
        # Input: (from CT input field)
        # Expected output: (from CT expected output field)
        assert True  # replace with real assertion
