/**
 * {{CT_ID}} — {{TITLE}}
 * Feature: {{FEATURE}}
 * Auto-generated by testspec. Fill in arrange/act/assert.
 */

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.assertThat;

@DisplayName("{{CT_ID}} — {{TITLE}}")
class {{CT_ID_CAMEL}}Test {

    @BeforeEach
    void setUp() {
        // arrange: set up state from spec precondition
    }

    @Test
    @DisplayName("should {{TITLE}}")
    void should{{CT_ID_CAMEL}}() {
        // Input: (from CT input field)
        // Expected output: (from CT expected output field)
        assertThat(true).isTrue(); // replace with real assertion
    }
}
